import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { existsSync, mkdirSync, createWriteStream } from 'fs';
import { getAssetById } from './storage.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CONTRACTS_DIR = join(__dirname, '../contracts');
if (!existsSync(CONTRACTS_DIR)) {
  mkdirSync(CONTRACTS_DIR, { recursive: true });
}

// 尝试注册中文字体（如果系统有的话）
// 如果不注册，pdfkit会使用内置的fallback机制处理中文
const registerChineseFont = (doc) => {
  try {
    // 常见的中文字体路径（macOS）
    const fontPaths = [
      '/System/Library/Fonts/Supplemental/PingFang.ttc',
      '/System/Library/Fonts/STHeiti Light.ttc',
      '/System/Library/Fonts/STSong.ttc',
      // Windows 字体路径
      'C:/Windows/Fonts/simsun.ttc',
      'C:/Windows/Fonts/simhei.ttf',
      'C:/Windows/Fonts/msyh.ttc',
      // Linux 字体路径
      '/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf',
    ];
    
    for (const fontPath of fontPaths) {
      if (existsSync(fontPath)) {
        try {
          doc.registerFont('ChineseFont', fontPath);
          doc.registerFont('ChineseFontBold', fontPath);
          return true;
        } catch (e) {
          // 继续尝试下一个
        }
      }
    }
  } catch (e) {
    // 字体注册失败，使用默认处理
  }
  return false;
};

/**
 * 生成资产数字化托管协议PDF
 * @param {Object} assetData - 资产数据（包含raw和sanitized）
 * @param {Object} options - 选项
 * @returns {Promise<string>} PDF文件路径
 */
export const generateContractPDF = async (assetData, options = {}) => {
  const { raw, sanitized } = assetData;
  
  if (!raw || !sanitized) {
    throw new Error('Asset data is incomplete');
  }

  // 生成文件名
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filename = `contract_${sanitized.id}_${timestamp}.pdf`;
  const filepath = join(CONTRACTS_DIR, filename);

  // 创建PDF文档
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    autoFirstPage: true
  });

  // 创建写入流
  const stream = createWriteStream(filepath);
  doc.pipe(stream);

  // 生成空白页（避免中文乱码问题）
  // 只添加基本的英文信息，其余为空白区域供手写填写
  
  // 顶部标题
  doc.fontSize(18)
     .font('Helvetica-Bold')
     .text('Digital Asset Contract', { align: 'center' });
  
  doc.moveDown(2);
  
  // 合同编号和日期
  doc.fontSize(12)
     .font('Helvetica')
     .text(`Contract ID: TWS-${sanitized.id}`, { align: 'left' });
  
  doc.moveDown(0.5);
  doc.text(`Date: ${new Date().toISOString().split('T')[0]}`, { align: 'left' });
  
  doc.moveDown(3);
  
  // 资产基本信息（英文）
  doc.fontSize(11)
     .font('Helvetica')
     .text('Asset Information:', { align: 'left' });
  
  doc.moveDown(0.5);
  doc.text(`Asset Code: ${sanitized.codeName || sanitized.displayId || 'N/A'}`, { align: 'left' });
  
  doc.moveDown(0.5);
  doc.text(`Area: ${raw.area || 0} sqm`, { align: 'left' });
  
  doc.moveDown(0.5);
  doc.text(`Amount: RMB ${(raw.debtAmount || 0).toLocaleString()} (10K)`, { align: 'left' });
  
  // 添加大量空白区域供手写填写
  doc.moveDown(8);
  
  // 签字区域
  doc.fontSize(11)
     .font('Helvetica')
     .text('Signature Area:', { align: 'left' });
  
  doc.moveDown(2);
  doc.text('_________________________', { align: 'left' });
  
  doc.moveDown(3);
  doc.text('_________________________', { align: 'left' });
  
  // 页脚
  doc.fontSize(8)
     .font('Helvetica')
     .text('This contract is automatically generated by TWS system.', 50, doc.page.height - 50, { align: 'center' });

  // 结束文档
  doc.end();

  // 等待PDF生成完成
  return new Promise((resolve, reject) => {
    stream.on('finish', () => {
      resolve(filepath);
    });
    stream.on('error', reject);
  });
};

/**
 * 根据资产ID生成合同
 * @param {string} assetId - 资产ID
 * @returns {Promise<string>} PDF文件路径
 */
export const generateContractByAssetId = async (assetId) => {
  const assetData = getAssetById(assetId);
  
  if (!assetData.raw || !assetData.sanitized) {
    throw new Error(`Asset with id ${assetId} not found`);
  }

  return await generateContractPDF(assetData);
};

